version: 2

project_name: diffx

before:
  hooks:
    - go generate ./frontend

builds:
  - id: diffx
    main: ./cmd/diffx
    binary: diffx
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - id: diffx
    ids:
      - diffx
    formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64{{ else }}{{ .Arch }}{{ end }}
    files:
      - none*

checksum:
  name_template: SHA256SUMS.txt
  algorithm: sha256

